
trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  CMAKE_GENERATOR: Ninja
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

jobs:
  - job: linux_static_vendored
    steps:
      - script: sudo apt-get install ninja-build ccache -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '.. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_USE_INTERNAL_GMP=1 -DIGRAPH_VERIFY_FINALLY_STACK=1'

      - task: Cache@2
        inputs:
          key: 'ccache | "$(Agent.OS)"'
          path: $(CCACHE_DIR)
        displayName: Ccache

      - task: CMake@1
        displayName: Build
        inputs:
          cmakeArgs: '--build . --target build_tests'

      - script: cd build && ctest -j `nproc` --output-on-failure
        displayName: Test

  - job: linux_static_external
    steps:
      - script: sudo apt-get install ninja-build ccache libgmp-dev libglpk-dev libarpack2-dev libblas-dev liblapack-dev -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '.. -DIGRAPH_USE_INTERNAL_BLAS=0 -DIGRAPH_USE_INTERNAL_LAPACK=0 -DIGRAPH_USE_INTERNAL_ARPACK=0 -DIGRAPH_USE_INTERNAL_GLPK=0 -DIGRAPH_USE_INTERNAL_CXSPARSE=0 -DIGRAPH_USE_INTERNAL_GMP=0 -DIGRAPH_VERIFY_FINALLY_STACK=1'

      - task: Cache@2
        inputs:
          key: 'ccache | "$(Agent.OS)"'
          path: $(CCACHE_DIR)
        displayName: Ccache

      - task: CMake@1
        displayName: Build
        inputs:
          cmakeArgs: '--build . --target build_tests'

      - script: cd build && ctest -j `nproc` --output-on-failure
        displayName: Test        

  - job: linux_shared_vendored
    steps:
      - script: sudo apt-get install ninja-build ccache -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '.. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_USE_INTERNAL_GMP=1 -DIGRAPH_VERIFY_FINALLY_STACK=1 -DBUILD_SHARED_LIBS=1'

      - task: Cache@2
        inputs:
          key: 'ccache | "$(Agent.OS)"'
          path: $(CCACHE_DIR)
        displayName: Ccache

      - task: CMake@1
        displayName: Build
        inputs:
          cmakeArgs: '--build . --target build_tests'

      - script: cd build && ctest -j `nproc` --output-on-failure
        displayName: Test

  - job: documentation
    steps:
      - script: sudo apt-get install ninja-build xmlto texinfo source-highlight libxml2-utils xsltproc fop -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '..'

      - task: CMake@1
        displayName: Doc build
        inputs:
          cmakeArgs: '--build . --target doc'

