
trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CMake@1
  displayName: Configure
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  displayName: Build
  inputs:
    cmakeArgs: '--build . --target build_tests'
- script: ctest -j2 --output-on-failure
  displayName: Test


