
trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  CMAKE_GENERATOR: Ninja
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

jobs:
  - job: Static build
    steps:
      - script: sudo apt-get install ninja-build ccache -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '.. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_USE_INTERNAL_GMP=1 -DIGRAPH_VERIFY_FINALLY_STACK=1'

      - task: Cache@2
        inputs:
          key: 'ccache | "$(Agent.OS)"'
          path: $(CCACHE_DIR)
        displayName: Ccache

      - task: CMake@1
        displayName: Build
        inputs:
          cmakeArgs: '--build . --target build_tests'

      - script: cd build && ctest -j `nproc` --output-on-failure
        displayName: Test

  - job: Dynamic build
    steps:
      - script: sudo apt-get install ninja-build ccache -y
        displayName: Install dependencies

      - task: CMake@1
        displayName: CMake
        inputs:
          cmakeArgs: '.. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_USE_INTERNAL_GMP=1 -DIGRAPH_VERIFY_FINALLY_STACK=1 -DBUILD_SHARED_LIBS=1'

      - task: Cache@2
        inputs:
          key: 'ccache | "$(Agent.OS)"'
          path: $(CCACHE_DIR)
        displayName: Ccache

      - task: CMake@1
        displayName: Build
        inputs:
          cmakeArgs: '--build . --target build_tests'

      - script: cd build && ctest -j `nproc` --output-on-failure
        displayName: Test
